name: Qualys IAC Scan 
on:
  push:
    branches:
      - feature/QINT-22485-IDP
jobs:
    Qualys_iac_scan:
        runs-on: ubuntu-latest
        name: Qualys IaC Scan
        steps:
          - name: Checkout
            uses: actions/checkout@v5 
            with:
                fetch-depth: 0
    
          - name: Qualys IAC scan action step
            uses: ./
            id: qiac
            env:
                URL: ${{ secrets.URL }}
                AUTHTYPE: IDP
                CLIENTID: ${{ secrets.CLIENTID }}
                CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
                TOKEN_URL: ${{ secrets.TOKEN_URL }}
                SCOPE: ${{ secrets.SCOPE }}
                AUDIENCE: ${{ secrets.AUDIENCE }}

          - name: Upload SARIF file
            uses: github/codeql-action/upload-sarif@v3
            if: always()
            with:
                sarif_file: response.sarif

          - name: Upload artifacts
            uses: actions/upload-artifact@v4
            if: always()
            with:
                name: qualys-iac-scan-results
                path: |
                    response.sarif
                    result.json
