name: Qualys IaC Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  qualys-iac-scan:
    runs-on: ubuntu-latest
    container:
      image: aanandedkarqualys/qiac:1.0.9.0-test
      options: --user root
      env:
        QUALYS_URL: ${{ vars.QUALYS_URL }}
        AUTH_TYPE: ${{ vars.AUTH_TYPE }}
        # For BasicAuth
        QUALYS_USERNAME: ${{ vars.QUALYS_USERNAME }}
        QUALYS_PASSWORD: ${{ secrets.QUALYS_PASSWORD }}
        # For OIDC / IDP
        QUALYS_CLIENTID: ${{ vars.QUALYS_CLIENTID }}
        QUALYS_CLIENTSECRET: ${{ secrets.QUALYS_CLIENTSECRET }}
        # For IDP only
        TOKEN_URL: ${{ vars.TOKEN_URL }}
        SCOPE: ${{ vars.SCOPE }}
        AUDIENCE: ${{ vars.AUDIENCE }}
        BREAK_ON_ERROR: ${{ vars.BREAK_ON_ERROR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run Qualys IaC Scan
        run: sh /home/qiac/github.sh

      - name: Upload scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qualys-iac-report
          path: |
            qualys_iac_github_report.json
            cli_output
            scan_response_*.json
