name: IAC Scan 

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ] 
   # schedule:
   #  - cron:  '*/5 * * * *'

jobs:
  iac_scan:
    runs-on: ubuntu-latest
    name: IaC Scan Connector
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2 
        with:
            fetch-depth: 0
#       - run: |
#              echo "action_state=`git log -n 2 --pretty=format:"%H" | tail -1`" >> $GITHUB_ENV
#       - run: git diff --name-only --diff-filter=ACMRT ${{ github.sha }} ${{ env.action_state }}
 
#       - run: |
#             find . -iname \*.tf \*.template \*.yml \*yaml \*.json
      - name: IAC scan action step
        uses: ./ # Uses an action in the root directory
        id: iac
        env:
          URL: ${{ secrets.URL }}
          UNAME: ${{ secrets.USERNAME }}
          PASS: ${{ secrets.PASSWORD }}

#       - name: Generate Error Annotations
#         run: |
#           text="This is an Error"
#           echo "::error file=app.js,line=10,col=15::$text"  
          
#       - name: Display the path
#         run: |
#             import os
#             print(os.environ['PATH'])
#             shell: python
#       - name: Annotate
#         uses: Attest/annotations-action@v1.0.7
#         with:
#                token: ${{ secrets.GITHUB_TOKEN }}
#                input: './annotations.json'
#                title: 'Annotate Files'

#    workflow_dispatch:
#     inputs:
#       directory:
#         description: Directory
#         default: "root"
#         required: false
